---

name: Retry recently failed domains
on:
  schedule:
    - cron: '51 12,20 * * *'
  workflow_dispatch:
jobs:
  http-checker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install aiohttp tqdm

      - name: Check some domains over HTTP
        run: python scripts/http_checker.py -s --grep $(git log -p urls.txt | grep ^-http | cut -d/ -f3 | head -n 50)

      - name: Setup git
        run: |
          git config user.name "GitHub Action"
          git config user.email "<>"

      - name: Commit
        run: |
          if [[ $(git status --porcelain --untracked-files=no) ]]
          then
              git commit -am "Refreshing recently removed domains."
              git push origin master
          fi
